# Base configs
baseurl: "https://zaaakk.github.io/basicportfolio"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Basic Portfolio"
subtitle: "Art"
author: "Mary Artist"
header:
 title: "Portfolio"
 subtitle: "by Mary Artist"
footer:
 name: "Portfolio Website"
 bio: "I'm an artist, hi!"
 github: "Here's my social media."
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/ram_patra"
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/rampatra"
