# Base configs
baseurl: "https://zaaakk.github.io/basicportfolio"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Workshop Portfolio"
subtitle: "creative projects"
author: "random"
header:
 title: "my art stuff"
 subtitle: "by random"
footer:
 name: "Portfolio Website"
 bio: "asl;kfjd;aksdjf;klasdjfkl;ajsdfkljas;lkdfjlaksjdf"
 github: "Here's my social media."
 email: "mary@art.com"
 resume: "/resume.pdf"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/"
  twitter: "https://www.twitter.com/"
  instagram: "https://www.instagram.com/"
  linkedin: "https://linkedin.com/dsfjkfldsj"
  github: "https://www.github.com/"
